[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
healthcheckInterval = 15

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONIOENCODING = "utf-8"
PORT = "8000"
TARGET_WIDTH = "1280"
TARGET_HEIGHT = "720"
TARGET_FPS = "30"
VIDEO_BITRATE = "2000k"
AUDIO_BITRATE = "128k"
MAX_UPLOAD_SIZE = "100MB" 