[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --log-level info"
healthcheckPath = "/status"
healthcheckTimeout = 120
restartPolicyMaxRetries = 5
healthcheckInterval = 15

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONIOENCODING = "utf-8"
PORT = "8000"
TARGET_WIDTH = "1280"
TARGET_HEIGHT = "720"
TARGET_FPS = "30"
VIDEO_BITRATE = "2000k"
AUDIO_BITRATE = "128k"
MAX_UPLOAD_SIZE = "100" 